"""Add chunk_index, page_number to document_chunks

Revision ID: 5156c45f9c91
Revises: bc2dc8ae8be8
Create Date: 2025-07-30 18:18:55.341946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5156c45f9c91'
down_revision: Union[str, Sequence[str], None] = 'bc2dc8ae8be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
